### ISSUE TITLE
[Wiki] Using the mpdf action returns an error

### ISSUE THREAD

**Issue by j4lc** [Yellow-Dog-Man/resonite-wiki#31]
### Describe the bug?

When using the action `?action=mpdf` on any Wiki page, an error will be returned.

### To Reproduce

1. Navigate to https://wiki.resonite.com/Command_Line_Arguments?action=mpdf (or any page with `?action=mpdf` appened to the URL)
2. Notice the error

### Expected behavior

Page as a PDF should be returned.

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### Log Files

As returned by the wiki:
```
[09ab028c3fa7dc8b1621bb6b] /Command_Line_Arguments?action=mpdf Mpdf\MpdfException: The HTML code size is larger than pcre.backtrack_limit 4. You should use WriteHTML() with smaller string lengths. Pass your HTML in smaller chunks.

Backtrace:

from /var/www/html/extensions/Mpdf/vendor/mpdf/mpdf/src/Mpdf.php(27072)
#0 /var/www/html/extensions/Mpdf/vendor/mpdf/mpdf/src/Mpdf.php(13437): Mpdf\Mpdf->AdjustHTML(string, integer)
Yellow-Dog-Man/Resonite-Issues#1 /var/www/html/extensions/Mpdf/MpdfAction.php(123): Mpdf\Mpdf->WriteHTML(string)
Yellow-Dog-Man/Resonite-Issues#2 /var/www/html/includes/MediaWiki.php(556): MpdfAction->show()
Yellow-Dog-Man/Resonite-Issues#3 /var/www/html/includes/MediaWiki.php(333): MediaWiki->performAction(Article, MediaWiki\Title\Title)
Yellow-Dog-Man/Resonite-Issues#4 /var/www/html/includes/MediaWiki.php(923): MediaWiki->performRequest()
Yellow-Dog-Man/Resonite-Issues#5 /var/www/html/includes/MediaWiki.php(576): MediaWiki->main()
Yellow-Dog-Man/Resonite-Issues#6 /var/www/html/index.php(50): MediaWiki->run()
Yellow-Dog-Man/Resonite-Issues#7 /var/www/html/index.php(46): wfIndexMain()
Yellow-Dog-Man/Resonite-Issues#8 {main}
```

**Comment by ProbablePrime** [comment]
This is fixed now! But it sucks
